[2024-10-18T13:21:44.882+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:21:44.908+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2021-11-07T00:00:00+00:00 [queued]>
[2024-10-18T13:21:44.925+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2021-11-07T00:00:00+00:00 [queued]>
[2024-10-18T13:21:44.926+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:21:44.976+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_2nd_task> on 2021-11-07 00:00:00+00:00
[2024-10-18T13:21:44.986+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1507) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:21:44.989+0000] {standard_task_runner.py:72} INFO - Started process 1522 to run task
[2024-10-18T13:21:44.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'this_is_2nd_task', 'scheduled__2021-11-07T00:00:00+00:00', '--job-id', '1647', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpge9py97y']
[2024-10-18T13:21:45.011+0000] {standard_task_runner.py:105} INFO - Job 1647: Subtask this_is_2nd_task
[2024-10-18T13:21:45.113+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.this_is_2nd_task scheduled__2021-11-07T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:21:45.266+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='this_is_2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2021-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-11-07T00:00:00+00:00'
[2024-10-18T13:21:45.267+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:21:45.300+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:21:45.301+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my second task and will run after task one ']
[2024-10-18T13:21:45.313+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:21:45.316+0000] {subprocess.py:93} INFO - Hello world, this is my second task and will run after task one
[2024-10-18T13:21:45.319+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:21:45.340+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:21:45.341+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=this_is_2nd_task, run_id=scheduled__2021-11-07T00:00:00+00:00, execution_date=20211107T000000, start_date=20241018T132144, end_date=20241018T132145
[2024-10-18T13:21:45.360+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:21:45.373+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:21:45.381+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
