[2024-10-18T13:27:02.794+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:27:02.825+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2021-12-07T00:00:00+00:00 [queued]>
[2024-10-18T13:27:02.865+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2021-12-07T00:00:00+00:00 [queued]>
[2024-10-18T13:27:02.866+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:27:02.907+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_3rd_task> on 2021-12-07 00:00:00+00:00
[2024-10-18T13:27:02.927+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6809) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:27:02.930+0000] {standard_task_runner.py:72} INFO - Started process 6828 to run task
[2024-10-18T13:27:02.930+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_3rd_task', 'scheduled__2021-12-07T00:00:00+00:00', '--job-id', '2904', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp5_mtfy3y']
[2024-10-18T13:27:02.939+0000] {standard_task_runner.py:105} INFO - Job 2904: Subtask this_is_3rd_task
[2024-10-18T13:27:03.012+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2021-12-07T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:27:03.183+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-07T00:00:00+00:00'
[2024-10-18T13:27:03.189+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:27:03.222+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:27:03.224+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my third task and will run after task1 and at same time task2']
[2024-10-18T13:27:03.249+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:27:03.250+0000] {subprocess.py:93} INFO - Hello world, this is my third task and will run after task1 and at same time task2
[2024-10-18T13:27:03.257+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:27:03.364+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:27:03.368+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_3rd_task, run_id=scheduled__2021-12-07T00:00:00+00:00, execution_date=20211207T000000, start_date=20241018T132702, end_date=20241018T132703
[2024-10-18T13:27:03.458+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:27:03.483+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:27:03.484+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
