[2024-10-18T13:26:38.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:26:38.211+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-10-08T00:00:00+00:00 [queued]>
[2024-10-18T13:26:38.227+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-10-08T00:00:00+00:00 [queued]>
[2024-10-18T13:26:38.228+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:26:38.268+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_2nd_task> on 2021-10-08 00:00:00+00:00
[2024-10-18T13:26:38.279+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6067) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:26:38.280+0000] {standard_task_runner.py:72} INFO - Started process 6087 to run task
[2024-10-18T13:26:38.283+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_2nd_task', 'scheduled__2021-10-08T00:00:00+00:00', '--job-id', '2725', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp8dzqil8n']
[2024-10-18T13:26:38.287+0000] {standard_task_runner.py:105} INFO - Job 2725: Subtask this_is_2nd_task
[2024-10-18T13:26:38.350+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-10-08T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:26:38.461+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-08T00:00:00+00:00'
[2024-10-18T13:26:38.465+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:26:38.486+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:26:38.487+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my second task and will run after task one ']
[2024-10-18T13:26:38.497+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:26:38.501+0000] {subprocess.py:93} INFO - Hello world, this is my second task and will run after task one
[2024-10-18T13:26:38.502+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:26:38.533+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:26:38.535+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_2nd_task, run_id=scheduled__2021-10-08T00:00:00+00:00, execution_date=20211008T000000, start_date=20241018T132638, end_date=20241018T132638
[2024-10-18T13:26:38.588+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:26:38.600+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:26:38.601+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
