[2024-10-18T13:27:06.580+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:27:06.597+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-12-16T00:00:00+00:00 [queued]>
[2024-10-18T13:27:06.610+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-12-16T00:00:00+00:00 [queued]>
[2024-10-18T13:27:06.611+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:27:06.674+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_2nd_task> on 2021-12-16 00:00:00+00:00
[2024-10-18T13:27:06.695+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6915) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:27:06.705+0000] {standard_task_runner.py:72} INFO - Started process 6936 to run task
[2024-10-18T13:27:06.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_2nd_task', 'scheduled__2021-12-16T00:00:00+00:00', '--job-id', '2933', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp5e9nm3oj']
[2024-10-18T13:27:06.722+0000] {standard_task_runner.py:105} INFO - Job 2933: Subtask this_is_2nd_task
[2024-10-18T13:27:06.836+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_2nd_task scheduled__2021-12-16T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:27:07.086+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_2nd_task' AIRFLOW_CTX_EXECUTION_DATE='2021-12-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-12-16T00:00:00+00:00'
[2024-10-18T13:27:07.092+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:27:07.236+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:27:07.241+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my second task and will run after task one ']
[2024-10-18T13:27:07.310+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:27:07.329+0000] {subprocess.py:93} INFO - Hello world, this is my second task and will run after task one
[2024-10-18T13:27:07.330+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:27:07.518+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:27:07.548+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_2nd_task, run_id=scheduled__2021-12-16T00:00:00+00:00, execution_date=20211216T000000, start_date=20241018T132706, end_date=20241018T132707
[2024-10-18T13:27:07.643+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:27:07.751+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:27:07.762+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
